---
- name: Setting up directories and downloading Nextcloud
  hosts: nextcloud
  become: yes

  vars:
    # Change these variables to your setup
    # Make sure they are the same in install.yml
    data_dir: ~/nextcloud/data
    nextcloud_root: ~/nextcloud/ # This is the root directory of the nextcloud installation, like /var/www/html

  tasks:
    - name: Ensure nextcloud_root exists
      ansible.builtin.file:
        path: {{ nextcloud_root }}
        state: directory
        mode: '0755'
    - name: Ensure data_dir exists
      ansible.builtin.file:
        path: {{ data_dir }}
        state: directory
        mode: '0755'
    - name: Downloading latest nextcloud archive
      ansible.builtin.get_url:
        url: https://download.nextcloud.com/server/releases/latest.zip
        dest: "{{ nextcloud_root }}/latest.zip"
    - name: Extracting nextcloud archive into "{{ nextcloud_root }}/nextcloud"
      ansible.builtin.unarchive:
        src: {{ nextcloud_root }}/latest.zip
        dest: {{ nextcloud_root }}
        remote_src: yes
    - name: Set owner www-data:www-data for nextcloud_root
      ansible.builtin.file:
        path: {{ nextcloud_root }}
        owner: www-data
        group: www-data
        recurse: yes
    - name: Set owner www-data:www-data for data_dir
      ansible.builtin.file:
        path: {{ data_dir }}
        owner: www-data
        group: www-data
        recurse: yes
    - name: Delete {{ nextcloud_root }}/latest.zip
      ansible.builtin.file:
        path: {{ nextcloud_root }}/latest.zip
        state: absent
  